version: '3.8'

# Production configuration for Legal Search RAG
# Use with: docker-compose -f docker-compose.yml -f docker-compose.production.yml up -d

services:
  api:
    environment:
      - USE_GCP_STORAGE=true
      - GCP_PROJECT_ID=${GCP_PROJECT_ID:-legal-search}
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME:-justin-legal-docs}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/gcp-key.json
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS:-/tmp/gcp-key.json}:/app/credentials/gcp-key.json:ro
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  frontend:
    restart: always
    environment:
      - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  nginx:
    restart: always
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
