[project]
name = "legal-search-rag"
version = "0.1.0"
description = "Legal search RAG project"
channels = ["conda-forge"]
platforms = ["osx-64"]

[dependencies]
python = ">=3.9,<3.13"              # Pin Python version below 3.13 for better compatibility
pip = "*"                           # Required for pip installations
tiktoken = ">=0.9.0,<0.10"
google-cloud-storage = ">=3.1.0,<4"
google-api-core = ">=2.24.2,<3"
ruff = ">=0.11.2,<0.12"             # Modern Python linter

[tasks]
lint = { cmd = "ruff check . --exclude=.pixi" }
format = { cmd = "ruff format . --exclude=.pixi" }
check-format = { cmd = "ruff format . --check --exclude=.pixi" }
process-docs = { cmd = "python api/process_docs.py" }
chunk-docs = { cmd = "python api/chunk.py" }
embed-docs = { cmd = "python api/embeddings.py" }
serve-api = { cmd = "cd api && uvicorn api:app --reload --host 0.0.0.0 --port 8000" }

[pypi-dependencies]
# Core dependencies
PyMuPDF = "*"                  # PDF processing
python-docx = "*"              # Word document processing
tqdm = "*"                     # Progress bars
google-generativeai = "*"      # Google's Generative AI API
Pillow = "*"                   # Python Imaging Library
chromadb = ">=0.4.22"          # Vector database with client extras
python-dotenv = "*"            # Environment variable management
langchain = "*"                # LangChain framework for RAG pipeline
openai = "*"                   # OpenAI API for embeddings
tokenizers = "*"               # Required for Chroma's embedding functions
grpcio = ">=1.54.0"            # Required for ChromaDB/OpenTelemetry
protobuf = ">=4.22.3"          # Required for gRPC serialization
grpcio-tools = "*"             # Includes grpc package needed for OpenTelemetry
googleapis-common-protos = "*" # Contains google.rpc protos
google-api-core = "*"          # Google API core libraries with protobuf support

# API dependencies
fastapi = "*"  # FastAPI framework
uvicorn = "*"  # ASGI server
pydantic = "*" # Data validation

# Development dependencies
pre-commit = "*"
ruff = ">=0.3.0" # Modern Python linter (replaces black, flake8, isort)
