services:
  # API Service
  - type: web
    name: legal-search-api
    env: docker
    dockerfilePath: ./api/Dockerfile
    dockerContext: ./api
    branch: main
    buildCommand: docker build -t legal-search-rag-api:latest .
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GCP_PROJECT_ID
        sync: false
      - key: GCS_BUCKET_NAME
        sync: false
      - key: PORT
        value: 8000
    healthCheckPath: /api/health
    disk:
      name: data
      mountPath: /app/cache
      sizeGB: 10
    plan: starter
    region: oregon

  # Frontend Service - Next.js
  - type: web
    name: legal-search-frontend
    env: docker
    plan: starter
    runtime: docker
    region: oregon
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    branch: main
    buildFilter:
      paths:
        - frontend/**
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: legal-search-api
          type: web
          property: hostport
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true
