services:
  # API Service
  - type: web
    name: legal-search-api
    env: docker
    dockerfilePath: ./api/Dockerfile
    dockerContext: ./api
    healthCheckPath: /health
    plan: starter
    envVars:
      - key: PORT
        value: 8000
      - key: TENANT_ID
        value: default
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: DATA_ROOT
        value: /app/data
      - key: INPUT_DIR
        value: /app/data/input
      - key: OUTPUT_DIR
        value: /app/data/processed
      - key: CHUNKS_DIR
        value: /app/data/chunks
      - key: CHROMA_DATA_DIR
        value: /app/data/chroma
      - key: COLLECTION_NAME
        value: legal_docs
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 10

  # Frontend Service
  - type: web
    name: legal-search-frontend
    env: docker
    plan: starter
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: legal-search-api
          type: web
          property: url
      - key: NODE_ENV
        value: production
