#!/usr/bin/env python3
"""
Mock handler for demonstrating RunPod serverless without requiring torch.

This simulates the behavior of the real handler for demonstration purposes.
"""

import time
import json
import logging
import runpod

# Configure logging
logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


def mock_handler(event):
    """Mock handler that simulates the Mixtral-8x7B model.

    This is for demonstration and testing of the RunPod serverless function
    structure without needing to install PyTorch/transformers.

    Args:
        event (dict): The RunPod event containing input data

    Returns:
        dict: Simulated response with generated text
    """
    try:
        # Log the received event
        logger.info(f"Received event: {json.dumps(event)}")

        # Extract inputs
        if not isinstance(event, dict) or "input" not in event:
            return {"error": "Invalid input format"}

        input_data = event.get("input", {})

        # Handle different input formats
        if "messages" in input_data:
            # Format similar to OpenAI chat completions
            messages = input_data.get("messages", [])

            # Extract system message and user prompt
            system_message = ""
            user_prompt = ""

            for message in messages:
                if not isinstance(message, dict):
                    continue

                role = message.get("role", "")
                content = message.get("content", "")

                if role == "system" and content:
                    system_message = content
                elif role == "user" and content:
                    user_prompt = content

            if not user_prompt:
                return {"error": "No valid user prompt found in messages"}

        elif "prompt" in input_data:
            # Single prompt format
            user_prompt = input_data.get("prompt", "")
            system_message = "You are a helpful assistant."

            if not user_prompt:
                return {"error": "No prompt provided"}
        else:
            return {"error": "Input must contain either 'messages' or 'prompt'"}

        # Extract generation parameters
        temperature = float(input_data.get("temperature", 0.7))
        max_tokens = int(input_data.get("max_tokens", 1000))

        # Log generation parameters
        logger.info(
            f"Generating response with temperature={temperature}, max_tokens={max_tokens}"
        )

        # Simulate thinking time
        start_time = time.time()
        time.sleep(1)  # Simulate processing time

        # Generate a mock response based on the prompt
        mock_responses = {
            "What are the key elements of a contract?": """
The key elements of a contract are:

1. Offer: A clear proposal made by one party
2. Acceptance: Agreement to the terms by the other party
3. Consideration: Something of value exchanged between parties
4. Legal capacity: Parties must be legally able to enter contracts
5. Legal purpose: The contract must be for lawful activities
6. Mutual assent: Both parties must understand and agree to terms
""",
            "Explain force majeure in legal contracts": """
Force majeure in legal contracts refers to unforeseeable circumstances that prevent parties from fulfilling contractual obligations.

Key aspects:
1. Events beyond reasonable control (wars, natural disasters)
2. Makes performance impossible or impractical
3. Not caused by negligence
4. Cannot be reasonably mitigated
5. Typically requires prompt notice to the other party

Force majeure clauses define specific qualifying events and outline consequences, such as suspending obligations temporarily or terminating the contract without liability.
""",
        }

        # Get the appropriate response or generate a default one
        if user_prompt in mock_responses:
            assistant_reply = mock_responses[user_prompt].strip()
        else:
            assistant_reply = f"This is a simulated response to: '{user_prompt}'\n\nIn a real implementation, this would be generated by the Mixtral model. The system context was: '{system_message}'."

        # Calculate tokens (simulated)
        prompt_tokens = len(user_prompt.split()) + len(system_message.split())
        completion_tokens = len(assistant_reply.split())

        # Calculate generation time
        gen_time = time.time() - start_time

        # Format response in OpenAI-compatible format
        response = {
            "id": f"mixtral-mock-{int(time.time())}",
            "object": "chat.completion",
            "created": int(time.time()),
            "model": "mixtral-8x7b-mock",
            "choices": [
                {
                    "index": 0,
                    "message": {"role": "assistant", "content": assistant_reply},
                    "finish_reason": "stop",
                }
            ],
            "usage": {
                "prompt_tokens": prompt_tokens,
                "completion_tokens": completion_tokens,
                "total_tokens": prompt_tokens + completion_tokens,
            },
            "system_info": {"generation_time": gen_time},
        }

        logger.info(f"Response generated in {gen_time:.2f} seconds (simulated)")
        return response

    except Exception as e:
        logger.error(f"Error in mock_handler: {str(e)}", exc_info=True)
        return {"error": str(e)}


# For local testing
if __name__ == "__main__":
    # Test with a sample prompt
    test_event = {
        "input": {
            "messages": [
                {"role": "system", "content": "You are a helpful legal assistant."},
                {"role": "user", "content": "What are the key elements of a contract?"},
            ],
            "temperature": 0.7,
            "max_tokens": 500,
        }
    }
    print(json.dumps(mock_handler(test_event), indent=2))


# For RunPod serverless
def handler(event):
    return mock_handler(event)


# Start the serverless worker when run directly
if __name__ == "__main__" and not hasattr(runpod, "_testing"):
    runpod.serverless.start({"handler": handler})
