services:
  api:
    build: ../api
    image: legal-search-rag-api:${TENANT_ID:-default}
    container_name: legal-search-api-${TENANT_ID:-default}
    ports:
      - "${API_PORT:-8001}:8000"
    env_file:
      - ${ENV_FILE:-../api/.env}
    environment:
      - PORT=8000
      - TENANT_ID=${TENANT_ID:-default}
    volumes:
      - legal_search_data:/app/cache
      - ../api:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: ["python", "-m", "uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build: ../frontend
    image: legal-search-rag-frontend:${TENANT_ID:-default}
    container_name: legal-search-frontend-${TENANT_ID:-default}
    ports:
      - "${FRONTEND_PORT:-3000}:10000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:${API_PORT:-8001}
      - NODE_ENV=development
      - TENANT_ID=${TENANT_ID:-default}
    depends_on:
      - api
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  legal_search_data:
    name: legal_search_data_${TENANT_ID:-default}
    driver: local
