version: '3.8'

# Production configuration for Legal Search RAG
# Use with: docker-compose -f docker-compose.yml -f docker-compose.production.yml up -d

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: legal-search-rag-api:${TENANT_ID:-default}
    ports:
      - "${API_PORT:-8000}:8000"
    env_file:
      - ${ENV_FILE:-./api/.env}
    volumes:
      - legal_search_data:/app/cache
      - ${GOOGLE_APPLICATION_CREDENTIALS:-./credentials/gcp-key.json}:/app/credentials/gcp-key.json:ro
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: legal-search-rag-frontend:${TENANT_ID:-default}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:${API_PORT:-8000}
      - NODE_ENV=production
    depends_on:
      - api
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./shared/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
      - frontend
    restart: unless-stopped

volumes:
  legal_search_data:
    name: legal_search_data_${TENANT_ID:-default}
    driver: local
