"""Deploy first document schema

Revision ID: 7e22516e1157
Revises:
Create Date: 2025-05-07 12:49:09.552414

"""

from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7e22516e1157"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("document_id", sa.BigInteger(), nullable=False),
        sa.Column("document_text", sa.Text(), nullable=False),
        sa.Column("document_source", sa.VARCHAR(length=104), nullable=False),
        sa.Column("document_file_path", sa.VARCHAR(length=1024), nullable=True),
        sa.PrimaryKeyConstraint("document_id"),
    )
    op.create_index(
        op.f("ix_documents_document_id"), "documents", ["document_id"], unique=False
    )
    op.create_table(
        "chunks",
        sa.Column("chunk_id", sa.BigInteger(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("document_id", sa.BigInteger(), nullable=False),
        sa.Column("chunk_sequence_in_document", sa.BigInteger(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.document_id"],
        ),
        sa.PrimaryKeyConstraint("chunk_id"),
    )
    op.create_index(
        "chunk_embedding_index",
        "chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_l2_ops"},
    )
    op.create_index(op.f("ix_chunks_chunk_id"), "chunks", ["chunk_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chunks_chunk_id"), table_name="chunks")
    op.drop_index(
        "chunk_embedding_index",
        table_name="chunks",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_l2_ops"},
    )
    op.drop_table("chunks")
    op.drop_index(op.f("ix_documents_document_id"), table_name="documents")
    op.drop_table("documents")
    # ### end Alembic commands ###
